# Generated by Django 5.2 on 2025-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='ID студента')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Фотография профиля')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('graduate', 'Выпускник'), ('dismissed', 'Отчислен'), ('academic_leave', 'Академический отпуск')], default='active', max_length=20, verbose_name='Статус')),
                ('enrollment_date', models.DateField(verbose_name='Дата зачисления')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('N', 'Не указан')], default='N', max_length=1, verbose_name='Пол')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('special_needs', models.TextField(blank=True, null=True, verbose_name='Особые потребности')),
            ],
        ),
    ]
