# Generated by Django 5.2 on 2025-04-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студента'},
        ),
    ]
