# Generated by Django 5.2 on 2025-04-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='ProfileAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название картинки')),
                ('image', models.FileField(upload_to='images', verbose_name='Файл')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile', verbose_name='Профиль студента')),
            ],
        ),
    ]
